// <auto-generated />
using BerrasBio.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BerrasBio.Migrations
{
    [DbContext(typeof(CinemaContext))]
    [Migration("20180328195613_Lounge info added")]
    partial class Loungeinfoadded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BerrasBio.Models.Lounge", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Info");

                    b.Property<int>("NrOfSeat");

                    b.Property<double>("TicketFee");

                    b.HasKey("ID");

                    b.ToTable("Lounge");
                });

            modelBuilder.Entity("BerrasBio.Models.Movie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Info");

                    b.Property<decimal>("TicketPrice");

                    b.Property<TimeSpan>("TimeSpan");

                    b.Property<string>("Title")
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("Movie");
                });

            modelBuilder.Entity("BerrasBio.Models.Showing", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("LoungeID");

                    b.Property<int>("MovieID");

                    b.Property<int>("SeatsLeft");

                    b.Property<DateTime>("StartTime");

                    b.HasKey("ID");

                    b.HasIndex("LoungeID");

                    b.HasIndex("MovieID");

                    b.ToTable("Showing");
                });

            modelBuilder.Entity("BerrasBio.Models.ShowingSeat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Booked");

                    b.Property<int>("Seat");

                    b.Property<int>("ShowingID");

                    b.HasKey("ID");

                    b.HasIndex("ShowingID");

                    b.ToTable("ShowingSeat");
                });

            modelBuilder.Entity("BerrasBio.Models.Showing", b =>
                {
                    b.HasOne("BerrasBio.Models.Lounge", "Lounge")
                        .WithMany("Showings")
                        .HasForeignKey("LoungeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BerrasBio.Models.Movie", "Movie")
                        .WithMany("Showings")
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BerrasBio.Models.ShowingSeat", b =>
                {
                    b.HasOne("BerrasBio.Models.Showing", "Showing")
                        .WithMany("ShowingSeats")
                        .HasForeignKey("ShowingID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
